relative path and window resize
mcworkaholic/IS345-G5-Music-Player pull request #14
Opened 2023-04-20 23:34 UTC by HillFlorence

I was able to maximize and minimize the window, however the page content when maximized doesn't fit the screen fully. If resizing needs done, let me know. If you don't mind how it is when maximized, i'll move on to another issue.

2023-04-21 01:11 UTC, mcworkaholic requested changes

2023-04-21 01:11 UTC, mcworkaholic commented on Music Player/MusicPlayer.cs
I think I wasn't clear in my issue, and that's my bad. I would like to be able to maximize the visualization window only, not the entire application, and of course be able to go back to the regular application window. So basically the ability to maximize and minimize the visualization window. This will probably require creating a new form with the same top bar as the others while putting the visualization window inside of it. If you undo the changes to everything besides config.cs and change config.cs to the correct lines, I will accept and merge your pull request.

2023-04-21 22:40 UTC, HillFlorence commented
Will do. Thank you
________________________________
From: mcworkaholic ***@***.***>
Sent: Thursday, April 20, 2023 8:11 PM
To: mcworkaholic/IS345-G5-Music-Player ***@***.***>
Cc: Hill, Florence W ***@***.***>; Author ***@***.***>
Subject: Re: [mcworkaholic/IS345-G5-Music-Player] relative path and window resize (PR #14)


@mcworkaholic requested changes on this pull request.

________________________________

On Music Player/Config.cs<https://github.com/mcworkaholic/IS345-G5-Music-Player/pull/14#discussion_r1173207432>:

So, what I'm looking for here is the relative path to the Utilities folder, then calling a built .exe file and executing it. If you change these lines to:

string workingDirectory = Environment.CurrentDirectory;
string exeDirectory = Directory.GetParent(workingDirectory).Parent.FullName + "\Utilities";
string exeFile = "music_dir_finder.exe";
string folderName = "Utilities";
string scriptPath = Path.Combine(exeDirectory, exeFile);

The program will correctly locate the file, and be able to execute the built .exe file

________________________________

On Music Player/MusicPlayer.cs<https://github.com/mcworkaholic/IS345-G5-Music-Player/pull/14#discussion_r1173214005>:

I think I wasn't clear in my issue, and that's my bad. I would like to be able to maximize the visualization window only, not the entire application, and of course be able to go back to the regular application window. So basically the ability to maximize and minimize the visualization window. This will probably require creating a new form with the same top bar as the others while putting the visualization window inside of it. If you undo the changes to everything besides config.cs and change config.cs to the correct lines, I will accept and merge your pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/mcworkaholic/IS345-G5-Music-Player/pull/14#pullrequestreview-1394923406>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7GT645MJLE5QUMHDEDRLLDXCHNE5ANCNFSM6AAAAAAXGE2HCQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-23 17:20 UTC, closed without merging

2023-04-23 17:20 UTC, mcworkaholic commented
fixed relative path and shuffling in last 2 commits